{% set name = "Kuyruk" %}
{% set version = "10.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ac197f55e9f2fbfe4c07db1f91d007c4db47b920ea8e0f2907e71ffb0e07827a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - kuyruk = kuyruk.__main__:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    # setuptools is required as a run dependency:
    # https://github.com/cenkalti/kuyruk/pull/45
    - setuptools
    - six >=1.10.0
    - amqp >=1.4.6
    - setproctitle >=1.1.8
    - blinker >=1.3
    - monotonic >=1.2

test:
  imports:
    - kuyruk
  commands:
    - kuyruk --help

about:
  home: https://github.com/cenkalti/kuyruk
  license: MIT
  license_file: LICENSE
  summary: Simple task queue for Python
  description: |
    Kuyruk is a simple and easy way of distributing tasks to run on servers.
    It uses RabbitMQ as message broker and depends on amqp which is a
    pure-Python RabbitMQ client library. Compatible with Python 2.7+ and 3.4+.
    All design decisions is based on simplicity. Speed is not first priority.
    Kuyruk only supports RabbitMQ and does not plan to support any other
    backend. Kuyruk is designed for long running mission critical jobs. For
    this reason Kuyruk sends acknowledgement only after the task is fully
    processed.
  doc_url: http://kuyruk.readthedocs.io/
  dev_url: https://github.com/cenkalti/kuyruk

extra:
  recipe-maintainers:
    - frol
    - cenkalti
