appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: BiaTEUekld6Z18qFKboXs2Xo+me8edjYSYKu05UTXwpjMME7WeZjjAcKQUkLmYKcZuO2eheybH11zsb0Hn/rxyhIco9pfFxCjfHArv8OBRyESip2b5hiPuCAhPdVqplnpWaqGwdJGw5kjew4l3x4sWSVJ5RMHGw3QdWh/DnE+dJFsthe+NclDLGLGlt9BdY0VmNN00e4cNZJFCZ6+BpA8G6k9Znxmfg92kkoQZ3bbLqRQcfbSYGGC90IA+nPkL7dX1nq+YSeAGulWw+ZSde36OZB5beWp4Z9pe9fCAIdBmKZQawGlAiNUU99KRLg83T8uiIrVKXi7IaVMQc11Uh/C//VzFLLNN2mmMhXzDpOYwSDZcRySS+ja44Rwq9RlwjKXEQnTzqBPW8eJAfxZ5AB+Jh2JnJ/qCdBdkXlSKPx70w0BapJUI+pctd2Hr8GHDY27j+3L8D9JnSa60RdZJH9eeApGEv+CRdnnEYtIHruIf37NjdqFNbYKBl0uBoAJps0Vg5PhsqICMeCKIOHyKiVS14hH/lzd5KCe+iFYL5ILt7xyJZfAoDd0jT6CZbNG8gQkmYEPO9hUr9D51hWe+/2sot0j88jENEbRAc7Xv134c7zQYJZ3CqtM3PWp/otd2hEd1zoJCTqvf8cZskg2Qd4hmYjYRX/yvsIIRIcJGrqV/c=}
provider:
  win: azure
conda_forge_output_validation: true
