travis:
  secure:
    BINSTAR_TOKEN: oPOhq5In+7mx2El8j2IgqbGYD3+IGbm0eSPn72jSTwlWpt1nqUpkNHPF7JXMfyTJa5dARSRfyiHPKQ6/gRx3edND46Gt87sVETFm/4eIcH2ZVcHbRqFb03/8z3coQfy36tZ0cBjbJPTflaRQI3qtPxsdcx3xvCQQS83WQP6HuGkjjzLOgX3I3ZUqwDMXNWs7WqarRDowINTBloouUjJoOjZLD4TfVEzUvPPUg9d8BmA0RCoUFp6/VuTnh7xZ3Zt/NOvoIqA2orOGWMMu3vkYBeUQGNgBmyCkIw+DNbXvnIRGS61cNpDWWI4IkZbu5Gi0Gecx9KHS3ubvdzI/trJgIeoDSvxndCV2W6nHSeWD7V4WSCbCW4C3caARSWkdUNI2r2srXEMiKZP9vE8ShptZ+ikMs2j0Z0lcRC9WkQqQs2Qi0dzIH25XAP+oXvxwdrIfty+GcAWOOGCeByn7ABK9dAsmUhFFk0Y27IDd8G9PenfDxdZlcmx7/3wAdrXPgZgyjSKcxzaavcRMBma6Vbna1cbqwLVZHy+f4yrIg8pDMKZKXPysn4KPJE6vIf11iywlihiQ6w1WNaGREVAIhLV6RLfomzO769s8Fq/c+gP/qlxZgmsyfgkxlPJCcPZ00IaX/7uBcs+2Q/8p9WmhML9NqAL8WfgwpwN31BcJRAEt+88=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
